name-template: v$NEXT_PATCH_VERSION

categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: bugfix

tag-template: $TITLE @$AUTHOR (#$NUMBER)
template: |
  ## Changes

  $CHANGES
